#!/usr/bin/env python
# -*- coding: utf-8 -*-

from pyfcm import FCMNotification
from pprint import pprint

registration_id="fFB7haLL3_k:APA91bEuXUCVrBDy1oM97S2a_-DhVahF5-LhAaKa9TY37UnOYdPq93_yScyQ7cl2a45RJ_3sxLm7YCMYQBC2xJQuGAbmmfDpulWf8OcvNeX180n5UHYEJ4aWrLylYgkRX9cC-yjKddAD"
#registration_id="/topics/news"
message_body="message_body"
message_title="Generated by server"
message_icon="ic_launcher"
sound="RingtoneManager.TYPE_NOTIFICATION"
condition=None
collapse_key=None
delay_while_idle=False
time_to_live=None
restricted_package_name=None
low_priority=False
dry_run=False
data_message=None
click_action="ShowMessageActivity"
badge=None
color="cyan"
tag=None
body_loc_key=None
body_loc_args=None
title_loc_key=None
title_loc_args=None
content_available=None
timeout=3



class FcmService:

    TOPIC = '/topics/news'

    def __init__(self):
        self.__api_key = "AAAAy0nKhj4:APA91bHc1RfNzVXAJnSWLZfKnIbcpOtyaJGfwLBq-YCFWK9khG0WDZoX_aXr9AaduL18yzdf-OXPtQuWKCEJ_FUmNvNNLjAHLNm5jhsReBJ4KN6_Z81yiZ3_x0RNRgsAieIyi6Cq7PzH"
        self.__push_service = FCMNotification(api_key="AAAAy0nKhj4:APA91bHc1RfNzVXAJnSWLZfKnIbcpOtyaJGfwLBq-YCFWK9khG0WDZoX_aXr9AaduL18yzdf-OXPtQuWKCEJ_FUmNvNNLjAHLNm5jhsReBJ4KN6_Z81yiZ3_x0RNRgsAieIyi6Cq7PzH")

    def send_data(self,json_data):
        result = self.__push_service.single_device_data_message(registration_id=FcmService.TOPIC,
                                                         data_message=json_data)

    def send_notification(self,title:str,body:str):
        json_data = {}
        json_data.update({'is_notification':'true',
                          'notification_title':title,
                          'notification_body':body})
        print(json_data)
        result = self.__push_service.single_device_data_message(registration_id=FcmService.TOPIC,
                                                         data_message=json_data)
